### ISSUE TITLE
What is missing from the current 0.5.5 release?

### ISSUE THREAD

**Issue by giacecco** [Artur-Brahms/Bitwig-MidiFighterTwister-CME#3]
First of all, how can I offer you a beer? 😀 Thank you for taking the effort of writing a Bitwig controller script for this.

Second, I am trying to understand where did you get to, in covering all the functionality described by the MidiFighter Twister manual, so that I can distinguish bugs from missing features. I am using Bitwig 4.1.1 with your release 0.5.5. MidiFighter Twister's firmware is up to date (2 Oct 2019).

E.g. setting `Switch Action Type` to `Shift Encoder Hold` seems not to have effect on Bitwig. Using [MIDI Monitor](https://www.snoize.com/midimonitor/) I see that - when holding the encoder down - the device sends CC messages on channel 5, but Bitwig seems to receive them anyway on the same parameter it was mapped against when not down (channel 1).

Thanks a lot in advance! Perhaps I should just learn how it works and debug it for myself  to help you 😀

G.

**Comment by pschuegr** [comment]
+1 this comment.  I ran into the same issue with the shift encoder, but @giacecco I think this is not implemented rather than a bug.  IIUC this script does not understand the different channels which means that a shifted encoder is not treated differently than a normal encoder.  I would like to implement this as well ;)

Would love to have some comment from @Artur-Brahms !

**Comment by Artur-Brahms** [comment]
Sorry for the late response, guys. I looked at that with the shift encoders, was not so easy to implement - but should work now from v0.6.0-Release (https://github.com/Artur-Brahms/Bitwig-MidiFighterTwister-CME/releases/tag/v0.6.0-Release). Of course I'm always happy about feedback ;-)
